name: Flex
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-font-awesome-sass
github_username:      rgautroncgiar
linkedin_username:    romain-gautron-56a582b0
email:  r.gautron@cgiar.org
baseurl: /flex
url: https://nappolini.github.io/